#!/bin/sh
sed -e 's/EXPER.charge/EXPER%charge/;
s/spec.e.P/spec%e%P/;
s/spec.e.theta/spec%e%theta/;
s/spec.p.P/spec%p%P/;
s/spec.p.theta/spec%p%theta/;
s/targ.A/targ%A/;
s/targ.Z/targ%Z/;
s/targ.mass_amu/targ%mass_amu/;
s/targ.mrec_amu/targ%mrec_amu/;
s/targ.rho/targ%rho/;
s/targ.thick/targ%thick/;
s/targ.angle/targ%angle/;
s/targ.abundancy/targ%abundancy/;
s/targ.can/targ%can/;
s/SPedge.e.delta.min/SPedge%e%delta%min/;
s/SPedge.e.delta.max/SPedge%e%delta%max/;
s/SPedge.e.yptar.min/SPedge%e%yptar%min/;
s/SPedge.e.yptar.max/SPedge%e%yptar%max/;
s/SPedge.e.xptar.min/SPedge%e%xptar%min/;
s/SPedge.e.xptar.max/SPedge%e%xptar%max/;
s/SPedge.p.delta.min/SPedge%p%delta%min/;
s/SPedge.p.delta.max/SPedge%p%delta%max/;
s/SPedge.p.yptar.min/SPedge%p%yptar%min/;
s/SPedge.p.yptar.max/SPedge%p%yptar%max/;;
s/SPedge.p.xptar.min/SPedge%p%xptar%min/
s/SPedge.p.xptar.max/SPedge%p%xptar%max/;
s/gen.xwid/gen%xwid/;
s/gen.ywid/gen%ywid/;
s/targ.fr_pattern/targ%fr_pattern/;
s/targ.fr1/targ%fr1/;
s/targ.fr2/targ%fr2/;
s/targ.xoffset/targ%xoffset/;
s/targ.yoffset/targ%yoffset/;
s/targ.zoffset/targ%zoffset/;
s/spec.e.offset.x/spec%e%offset%x/;
s/spec.e.offset.y/spec%e%offset%y/;
s/spec.e.offset.z/spec%e%offset%z/;
s/spec.e.offset.xptar/spec%e%offset%xptar/;
s/spec.e.offset.yptar/spec%e%offset%yptar/;
s/spec.p.offset.x/spec%p%offset%x/;
s/spec.p.offset.y/spec%p%offset%y/;
s/spec.p.offset.z/spec%p%offset%z/;
s/spec.p.offset.xptar/spec%p%offset%xptar/;
s/spec.p.offset.yptar/spec%p%offset%yptar/;
s/cuts.Em.min/cuts%Em%min/;
s/cuts.Em.max/cuts%Em%max/' < $1     > temp.inp
cp temp.inp $1
